spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    schema: classpath:db/db.schema-h2.sql
    data: classpath:db/db.data-h2.sql
#    url: jdbc:p6spy:h2:~/test;MODE=MYSQL
    url: jdbc:p6spy:h2:mem:test;MODE=MYSQL
    username: root
    password: test
    druid:
      db-type: h2
      initialSize: 5
      minIdle: 5
      maxActive: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: false
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 10
      filters: stat,wall


logging:
  file:
    clean-history-on-start: true
  level:
    web: DEBUG
    net:
      oschina:
        j2cache: TRACE
# ===========================================================================
# 微信公众号和微信小程序相关配置
# ===========================================================================
# 微信公众号
weixin:
  #
  request-access-token-url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
  #
  request-jsapi-ticket-url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi
  # 获取二维码
  # https://developers.weixin.qq.com/miniprogram/dev/api/qrcode.html
  request-mp-qr-code-url: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=%s
  # 获取临时多媒体素材
  request-download-media-url: https://api.weixin.qq.com/cgi-bin/media/get?access_token=%s&media_id=%s
  # ===========================================================================
  # 小程序相关设置
  # ===========================================================================
  # 小程序对应的appId
  mina-app-id: wxc1960f486e0b3362 #测试号
  # 小程序对应的密钥
  mina-app-secret: b9fe86a448ac8626f40cd696d3f37d0e #测试号
  mina-code-to-session-url: https://api.weixin.qq.com/sns/jscode2session?appid=${weixin.mina-app-id}&secret=${weixin.mina-app-secret}&js_code=%s&grant_type=authorization_code