debug: false
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
      classpath:/static/,classpath:/public/
  profiles:
    active: dev
  jpa:
    open-in-view: false
  cache:
    type: generic

server:
  port: 8082
  undertow:
    accesslog:
      enabled: false
      dir: logs
logging:
  file:
    name: ./logs/backend.log
  pattern:
    file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] [%-40.40logger{39}:%line] : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'

j2cache:
  l2-cache-open: true
  redis-client: lettuce
  open-spring-cache: true
  allow-null-values: false
  config-location: /j2cache-${spring.profiles.active}.properties
#  缓存清除模式
#  active:主动清除，二级缓存过期主动通知各节点清除，优点在于所有节点可以同时收到缓存清除
#  passive:被动清除，一级缓存过期进行通知各节点清除一二级缓存
#  blend:两种模式一起运作，对于各个节点缓存准确性以及及时性要求高的可以使用（推荐使用前面两种模式中一种）
  cache-clean-mode: passive


mybatis-plus:
# 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
# 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapperLocations: classpath*:/com/base/backend/modules/**/*Mapper.xml
#实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.base.backend.modules.entity
  typeEnumsPackage: com.base.backend.modules.enums
  executorType: REUSE
  global-config:
    banner: false
    db-config:
      idType: ASSIGN_ID
      logicDeleteField: deletedInd
      logicNotDeleteValue: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
  #  jdbc-type-for-null: 'null'

