debug: false
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
      classpath:/static/,classpath:/public/
  profiles:
    active: dev
  jpa:
    open-in-view: false
#  aop:
#    proxy-target-class: false
  redis:
    host: 39.97.251.229
    port: 16379
    password: Redis!@#123
    database: 1
    lettuce:
      pool:
        maxActive: 2048
        maxIdle: 200
        maxWait: 1500ms
        minIdle: 20
server:
  port: 8082
  undertow:
    accesslog:
      enabled: false
      dir: logs
logging:
  file:
    name: ./logs/backend.log
  pattern:
    file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] [%-40.40logger{39}:%line] : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
autoload:
  cache:
    config:
      namespace: backend-api
    enable: true
    proxy-target-class: true

mybatis-plus:
# 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
# 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapperLocations: classpath:/mapper/*Mapper.xml
#实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.base.backend.modules.entity
  typeEnumsPackage: com.base.backend.modules.enums
  executorType: REUSE
  global-config:
    banner: false
    db-config:
      idType: ASSIGN_ID
      logicDeleteField: deletedInd
      logicNotDeleteValue: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
  #  jdbc-type-for-null: 'null'

