spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:mysql://39.97.251.229:3306/backend-db?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    url: jdbc:p6spy:mysql://39.97.251.229:3306/backend-db?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: test
    password: 1q2w3e4r
    #    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      db-type: mysql
      initialSize: 5
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall


# ===========================================================================
# 微信公众号和微信小程序相关配置
# ===========================================================================
# 微信公众号
# 是否启用多机构多公众号
weixin:
  #
  request-access-token-url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
  #
  request-jsapi-ticket-url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi
  # 获取二维码
  # https://developers.weixin.qq.com/miniprogram/dev/api/qrcode.html
  request-mp-qr-code-url: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=%s
  # 获取临时多媒体素材
  request-download-media-url: https://api.weixin.qq.com/cgi-bin/media/get?access_token=%s&media_id=%s
  # ===========================================================================
  # 小程序相关设置
  # ===========================================================================
  # 小程序对应的appId
  #  mina-app-id: wx4b3df4b35f91915e #鑫考试
  mina-app-id: wxc1960f486e0b3362 #测试号
  # 小程序对应的密钥
  #  mina-app-secret: f2eabe0c9004c5af614856ffcba7d91c #鑫考试
  mina-app-secret: b9fe86a448ac8626f40cd696d3f37d0e #测试号
  mina-code-to-session-url: https://api.weixin.qq.com/sns/jscode2session?appid=${weixin.mina-app-id}&secret=${weixin.mina-app-secret}&js_code=%s&grant_type=authorization_code